image: cangcanglang/linarogcc-docker

dtb:
  - build
  - test
  - deploy

dtb:
  stage: build
  only: 
    refs:
      - hwzqv3
  script:
    - make
  tags:
    - knl_builder
  artifacts:
    paths:
      - devicetree.dtb
    name: "${CI_JOB_NAME}_${CI_COMMIT_SHA:0:8}"

